// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package job

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.CodeGenConfigurationNodes) != len(b.ko.Spec.CodeGenConfigurationNodes) {
		delta.Add("Spec.CodeGenConfigurationNodes", a.ko.Spec.CodeGenConfigurationNodes, b.ko.Spec.CodeGenConfigurationNodes)
	} else if len(a.ko.Spec.CodeGenConfigurationNodes) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.CodeGenConfigurationNodes, b.ko.Spec.CodeGenConfigurationNodes) {
			delta.Add("Spec.CodeGenConfigurationNodes", a.ko.Spec.CodeGenConfigurationNodes, b.ko.Spec.CodeGenConfigurationNodes)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Command, b.ko.Spec.Command) {
		delta.Add("Spec.Command", a.ko.Spec.Command, b.ko.Spec.Command)
	} else if a.ko.Spec.Command != nil && b.ko.Spec.Command != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Command.Name, b.ko.Spec.Command.Name) {
			delta.Add("Spec.Command.Name", a.ko.Spec.Command.Name, b.ko.Spec.Command.Name)
		} else if a.ko.Spec.Command.Name != nil && b.ko.Spec.Command.Name != nil {
			if *a.ko.Spec.Command.Name != *b.ko.Spec.Command.Name {
				delta.Add("Spec.Command.Name", a.ko.Spec.Command.Name, b.ko.Spec.Command.Name)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Command.PythonVersion, b.ko.Spec.Command.PythonVersion) {
			delta.Add("Spec.Command.PythonVersion", a.ko.Spec.Command.PythonVersion, b.ko.Spec.Command.PythonVersion)
		} else if a.ko.Spec.Command.PythonVersion != nil && b.ko.Spec.Command.PythonVersion != nil {
			if *a.ko.Spec.Command.PythonVersion != *b.ko.Spec.Command.PythonVersion {
				delta.Add("Spec.Command.PythonVersion", a.ko.Spec.Command.PythonVersion, b.ko.Spec.Command.PythonVersion)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Command.Runtime, b.ko.Spec.Command.Runtime) {
			delta.Add("Spec.Command.Runtime", a.ko.Spec.Command.Runtime, b.ko.Spec.Command.Runtime)
		} else if a.ko.Spec.Command.Runtime != nil && b.ko.Spec.Command.Runtime != nil {
			if *a.ko.Spec.Command.Runtime != *b.ko.Spec.Command.Runtime {
				delta.Add("Spec.Command.Runtime", a.ko.Spec.Command.Runtime, b.ko.Spec.Command.Runtime)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Command.ScriptLocation, b.ko.Spec.Command.ScriptLocation) {
			delta.Add("Spec.Command.ScriptLocation", a.ko.Spec.Command.ScriptLocation, b.ko.Spec.Command.ScriptLocation)
		} else if a.ko.Spec.Command.ScriptLocation != nil && b.ko.Spec.Command.ScriptLocation != nil {
			if *a.ko.Spec.Command.ScriptLocation != *b.ko.Spec.Command.ScriptLocation {
				delta.Add("Spec.Command.ScriptLocation", a.ko.Spec.Command.ScriptLocation, b.ko.Spec.Command.ScriptLocation)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Connections, b.ko.Spec.Connections) {
		delta.Add("Spec.Connections", a.ko.Spec.Connections, b.ko.Spec.Connections)
	} else if a.ko.Spec.Connections != nil && b.ko.Spec.Connections != nil {
		if len(a.ko.Spec.Connections.Connections) != len(b.ko.Spec.Connections.Connections) {
			delta.Add("Spec.Connections.Connections", a.ko.Spec.Connections.Connections, b.ko.Spec.Connections.Connections)
		} else if len(a.ko.Spec.Connections.Connections) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.Connections.Connections, b.ko.Spec.Connections.Connections) {
				delta.Add("Spec.Connections.Connections", a.ko.Spec.Connections.Connections, b.ko.Spec.Connections.Connections)
			}
		}
	}
	if len(a.ko.Spec.DefaultArguments) != len(b.ko.Spec.DefaultArguments) {
		delta.Add("Spec.DefaultArguments", a.ko.Spec.DefaultArguments, b.ko.Spec.DefaultArguments)
	} else if len(a.ko.Spec.DefaultArguments) > 0 {
		if !ackcompare.MapStringStringPEqual(a.ko.Spec.DefaultArguments, b.ko.Spec.DefaultArguments) {
			delta.Add("Spec.DefaultArguments", a.ko.Spec.DefaultArguments, b.ko.Spec.DefaultArguments)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ExecutionClass, b.ko.Spec.ExecutionClass) {
		delta.Add("Spec.ExecutionClass", a.ko.Spec.ExecutionClass, b.ko.Spec.ExecutionClass)
	} else if a.ko.Spec.ExecutionClass != nil && b.ko.Spec.ExecutionClass != nil {
		if *a.ko.Spec.ExecutionClass != *b.ko.Spec.ExecutionClass {
			delta.Add("Spec.ExecutionClass", a.ko.Spec.ExecutionClass, b.ko.Spec.ExecutionClass)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ExecutionProperty, b.ko.Spec.ExecutionProperty) {
		delta.Add("Spec.ExecutionProperty", a.ko.Spec.ExecutionProperty, b.ko.Spec.ExecutionProperty)
	} else if a.ko.Spec.ExecutionProperty != nil && b.ko.Spec.ExecutionProperty != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.ExecutionProperty.MaxConcurrentRuns, b.ko.Spec.ExecutionProperty.MaxConcurrentRuns) {
			delta.Add("Spec.ExecutionProperty.MaxConcurrentRuns", a.ko.Spec.ExecutionProperty.MaxConcurrentRuns, b.ko.Spec.ExecutionProperty.MaxConcurrentRuns)
		} else if a.ko.Spec.ExecutionProperty.MaxConcurrentRuns != nil && b.ko.Spec.ExecutionProperty.MaxConcurrentRuns != nil {
			if *a.ko.Spec.ExecutionProperty.MaxConcurrentRuns != *b.ko.Spec.ExecutionProperty.MaxConcurrentRuns {
				delta.Add("Spec.ExecutionProperty.MaxConcurrentRuns", a.ko.Spec.ExecutionProperty.MaxConcurrentRuns, b.ko.Spec.ExecutionProperty.MaxConcurrentRuns)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.GlueVersion, b.ko.Spec.GlueVersion) {
		delta.Add("Spec.GlueVersion", a.ko.Spec.GlueVersion, b.ko.Spec.GlueVersion)
	} else if a.ko.Spec.GlueVersion != nil && b.ko.Spec.GlueVersion != nil {
		if *a.ko.Spec.GlueVersion != *b.ko.Spec.GlueVersion {
			delta.Add("Spec.GlueVersion", a.ko.Spec.GlueVersion, b.ko.Spec.GlueVersion)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.JobMode, b.ko.Spec.JobMode) {
		delta.Add("Spec.JobMode", a.ko.Spec.JobMode, b.ko.Spec.JobMode)
	} else if a.ko.Spec.JobMode != nil && b.ko.Spec.JobMode != nil {
		if *a.ko.Spec.JobMode != *b.ko.Spec.JobMode {
			delta.Add("Spec.JobMode", a.ko.Spec.JobMode, b.ko.Spec.JobMode)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.JobRunQueuingEnabled, b.ko.Spec.JobRunQueuingEnabled) {
		delta.Add("Spec.JobRunQueuingEnabled", a.ko.Spec.JobRunQueuingEnabled, b.ko.Spec.JobRunQueuingEnabled)
	} else if a.ko.Spec.JobRunQueuingEnabled != nil && b.ko.Spec.JobRunQueuingEnabled != nil {
		if *a.ko.Spec.JobRunQueuingEnabled != *b.ko.Spec.JobRunQueuingEnabled {
			delta.Add("Spec.JobRunQueuingEnabled", a.ko.Spec.JobRunQueuingEnabled, b.ko.Spec.JobRunQueuingEnabled)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LogURI, b.ko.Spec.LogURI) {
		delta.Add("Spec.LogURI", a.ko.Spec.LogURI, b.ko.Spec.LogURI)
	} else if a.ko.Spec.LogURI != nil && b.ko.Spec.LogURI != nil {
		if *a.ko.Spec.LogURI != *b.ko.Spec.LogURI {
			delta.Add("Spec.LogURI", a.ko.Spec.LogURI, b.ko.Spec.LogURI)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaintenanceWindow, b.ko.Spec.MaintenanceWindow) {
		delta.Add("Spec.MaintenanceWindow", a.ko.Spec.MaintenanceWindow, b.ko.Spec.MaintenanceWindow)
	} else if a.ko.Spec.MaintenanceWindow != nil && b.ko.Spec.MaintenanceWindow != nil {
		if *a.ko.Spec.MaintenanceWindow != *b.ko.Spec.MaintenanceWindow {
			delta.Add("Spec.MaintenanceWindow", a.ko.Spec.MaintenanceWindow, b.ko.Spec.MaintenanceWindow)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaxCapacity, b.ko.Spec.MaxCapacity) {
		delta.Add("Spec.MaxCapacity", a.ko.Spec.MaxCapacity, b.ko.Spec.MaxCapacity)
	} else if a.ko.Spec.MaxCapacity != nil && b.ko.Spec.MaxCapacity != nil {
		if *a.ko.Spec.MaxCapacity != *b.ko.Spec.MaxCapacity {
			delta.Add("Spec.MaxCapacity", a.ko.Spec.MaxCapacity, b.ko.Spec.MaxCapacity)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaxRetries, b.ko.Spec.MaxRetries) {
		delta.Add("Spec.MaxRetries", a.ko.Spec.MaxRetries, b.ko.Spec.MaxRetries)
	} else if a.ko.Spec.MaxRetries != nil && b.ko.Spec.MaxRetries != nil {
		if *a.ko.Spec.MaxRetries != *b.ko.Spec.MaxRetries {
			delta.Add("Spec.MaxRetries", a.ko.Spec.MaxRetries, b.ko.Spec.MaxRetries)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.NonOverridableArguments) != len(b.ko.Spec.NonOverridableArguments) {
		delta.Add("Spec.NonOverridableArguments", a.ko.Spec.NonOverridableArguments, b.ko.Spec.NonOverridableArguments)
	} else if len(a.ko.Spec.NonOverridableArguments) > 0 {
		if !ackcompare.MapStringStringPEqual(a.ko.Spec.NonOverridableArguments, b.ko.Spec.NonOverridableArguments) {
			delta.Add("Spec.NonOverridableArguments", a.ko.Spec.NonOverridableArguments, b.ko.Spec.NonOverridableArguments)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.NotificationProperty, b.ko.Spec.NotificationProperty) {
		delta.Add("Spec.NotificationProperty", a.ko.Spec.NotificationProperty, b.ko.Spec.NotificationProperty)
	} else if a.ko.Spec.NotificationProperty != nil && b.ko.Spec.NotificationProperty != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.NotificationProperty.NotifyDelayAfter, b.ko.Spec.NotificationProperty.NotifyDelayAfter) {
			delta.Add("Spec.NotificationProperty.NotifyDelayAfter", a.ko.Spec.NotificationProperty.NotifyDelayAfter, b.ko.Spec.NotificationProperty.NotifyDelayAfter)
		} else if a.ko.Spec.NotificationProperty.NotifyDelayAfter != nil && b.ko.Spec.NotificationProperty.NotifyDelayAfter != nil {
			if *a.ko.Spec.NotificationProperty.NotifyDelayAfter != *b.ko.Spec.NotificationProperty.NotifyDelayAfter {
				delta.Add("Spec.NotificationProperty.NotifyDelayAfter", a.ko.Spec.NotificationProperty.NotifyDelayAfter, b.ko.Spec.NotificationProperty.NotifyDelayAfter)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.NumberOfWorkers, b.ko.Spec.NumberOfWorkers) {
		delta.Add("Spec.NumberOfWorkers", a.ko.Spec.NumberOfWorkers, b.ko.Spec.NumberOfWorkers)
	} else if a.ko.Spec.NumberOfWorkers != nil && b.ko.Spec.NumberOfWorkers != nil {
		if *a.ko.Spec.NumberOfWorkers != *b.ko.Spec.NumberOfWorkers {
			delta.Add("Spec.NumberOfWorkers", a.ko.Spec.NumberOfWorkers, b.ko.Spec.NumberOfWorkers)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Role, b.ko.Spec.Role) {
		delta.Add("Spec.Role", a.ko.Spec.Role, b.ko.Spec.Role)
	} else if a.ko.Spec.Role != nil && b.ko.Spec.Role != nil {
		if *a.ko.Spec.Role != *b.ko.Spec.Role {
			delta.Add("Spec.Role", a.ko.Spec.Role, b.ko.Spec.Role)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.RoleRef, b.ko.Spec.RoleRef) {
		delta.Add("Spec.RoleRef", a.ko.Spec.RoleRef, b.ko.Spec.RoleRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SecurityConfiguration, b.ko.Spec.SecurityConfiguration) {
		delta.Add("Spec.SecurityConfiguration", a.ko.Spec.SecurityConfiguration, b.ko.Spec.SecurityConfiguration)
	} else if a.ko.Spec.SecurityConfiguration != nil && b.ko.Spec.SecurityConfiguration != nil {
		if *a.ko.Spec.SecurityConfiguration != *b.ko.Spec.SecurityConfiguration {
			delta.Add("Spec.SecurityConfiguration", a.ko.Spec.SecurityConfiguration, b.ko.Spec.SecurityConfiguration)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SourceControlDetails, b.ko.Spec.SourceControlDetails) {
		delta.Add("Spec.SourceControlDetails", a.ko.Spec.SourceControlDetails, b.ko.Spec.SourceControlDetails)
	} else if a.ko.Spec.SourceControlDetails != nil && b.ko.Spec.SourceControlDetails != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.SourceControlDetails.AuthStrategy, b.ko.Spec.SourceControlDetails.AuthStrategy) {
			delta.Add("Spec.SourceControlDetails.AuthStrategy", a.ko.Spec.SourceControlDetails.AuthStrategy, b.ko.Spec.SourceControlDetails.AuthStrategy)
		} else if a.ko.Spec.SourceControlDetails.AuthStrategy != nil && b.ko.Spec.SourceControlDetails.AuthStrategy != nil {
			if *a.ko.Spec.SourceControlDetails.AuthStrategy != *b.ko.Spec.SourceControlDetails.AuthStrategy {
				delta.Add("Spec.SourceControlDetails.AuthStrategy", a.ko.Spec.SourceControlDetails.AuthStrategy, b.ko.Spec.SourceControlDetails.AuthStrategy)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SourceControlDetails.AuthToken, b.ko.Spec.SourceControlDetails.AuthToken) {
			delta.Add("Spec.SourceControlDetails.AuthToken", a.ko.Spec.SourceControlDetails.AuthToken, b.ko.Spec.SourceControlDetails.AuthToken)
		} else if a.ko.Spec.SourceControlDetails.AuthToken != nil && b.ko.Spec.SourceControlDetails.AuthToken != nil {
			if *a.ko.Spec.SourceControlDetails.AuthToken != *b.ko.Spec.SourceControlDetails.AuthToken {
				delta.Add("Spec.SourceControlDetails.AuthToken", a.ko.Spec.SourceControlDetails.AuthToken, b.ko.Spec.SourceControlDetails.AuthToken)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SourceControlDetails.Branch, b.ko.Spec.SourceControlDetails.Branch) {
			delta.Add("Spec.SourceControlDetails.Branch", a.ko.Spec.SourceControlDetails.Branch, b.ko.Spec.SourceControlDetails.Branch)
		} else if a.ko.Spec.SourceControlDetails.Branch != nil && b.ko.Spec.SourceControlDetails.Branch != nil {
			if *a.ko.Spec.SourceControlDetails.Branch != *b.ko.Spec.SourceControlDetails.Branch {
				delta.Add("Spec.SourceControlDetails.Branch", a.ko.Spec.SourceControlDetails.Branch, b.ko.Spec.SourceControlDetails.Branch)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SourceControlDetails.Folder, b.ko.Spec.SourceControlDetails.Folder) {
			delta.Add("Spec.SourceControlDetails.Folder", a.ko.Spec.SourceControlDetails.Folder, b.ko.Spec.SourceControlDetails.Folder)
		} else if a.ko.Spec.SourceControlDetails.Folder != nil && b.ko.Spec.SourceControlDetails.Folder != nil {
			if *a.ko.Spec.SourceControlDetails.Folder != *b.ko.Spec.SourceControlDetails.Folder {
				delta.Add("Spec.SourceControlDetails.Folder", a.ko.Spec.SourceControlDetails.Folder, b.ko.Spec.SourceControlDetails.Folder)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SourceControlDetails.LastCommitID, b.ko.Spec.SourceControlDetails.LastCommitID) {
			delta.Add("Spec.SourceControlDetails.LastCommitID", a.ko.Spec.SourceControlDetails.LastCommitID, b.ko.Spec.SourceControlDetails.LastCommitID)
		} else if a.ko.Spec.SourceControlDetails.LastCommitID != nil && b.ko.Spec.SourceControlDetails.LastCommitID != nil {
			if *a.ko.Spec.SourceControlDetails.LastCommitID != *b.ko.Spec.SourceControlDetails.LastCommitID {
				delta.Add("Spec.SourceControlDetails.LastCommitID", a.ko.Spec.SourceControlDetails.LastCommitID, b.ko.Spec.SourceControlDetails.LastCommitID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SourceControlDetails.Owner, b.ko.Spec.SourceControlDetails.Owner) {
			delta.Add("Spec.SourceControlDetails.Owner", a.ko.Spec.SourceControlDetails.Owner, b.ko.Spec.SourceControlDetails.Owner)
		} else if a.ko.Spec.SourceControlDetails.Owner != nil && b.ko.Spec.SourceControlDetails.Owner != nil {
			if *a.ko.Spec.SourceControlDetails.Owner != *b.ko.Spec.SourceControlDetails.Owner {
				delta.Add("Spec.SourceControlDetails.Owner", a.ko.Spec.SourceControlDetails.Owner, b.ko.Spec.SourceControlDetails.Owner)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SourceControlDetails.Provider, b.ko.Spec.SourceControlDetails.Provider) {
			delta.Add("Spec.SourceControlDetails.Provider", a.ko.Spec.SourceControlDetails.Provider, b.ko.Spec.SourceControlDetails.Provider)
		} else if a.ko.Spec.SourceControlDetails.Provider != nil && b.ko.Spec.SourceControlDetails.Provider != nil {
			if *a.ko.Spec.SourceControlDetails.Provider != *b.ko.Spec.SourceControlDetails.Provider {
				delta.Add("Spec.SourceControlDetails.Provider", a.ko.Spec.SourceControlDetails.Provider, b.ko.Spec.SourceControlDetails.Provider)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SourceControlDetails.Repository, b.ko.Spec.SourceControlDetails.Repository) {
			delta.Add("Spec.SourceControlDetails.Repository", a.ko.Spec.SourceControlDetails.Repository, b.ko.Spec.SourceControlDetails.Repository)
		} else if a.ko.Spec.SourceControlDetails.Repository != nil && b.ko.Spec.SourceControlDetails.Repository != nil {
			if *a.ko.Spec.SourceControlDetails.Repository != *b.ko.Spec.SourceControlDetails.Repository {
				delta.Add("Spec.SourceControlDetails.Repository", a.ko.Spec.SourceControlDetails.Repository, b.ko.Spec.SourceControlDetails.Repository)
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Timeout, b.ko.Spec.Timeout) {
		delta.Add("Spec.Timeout", a.ko.Spec.Timeout, b.ko.Spec.Timeout)
	} else if a.ko.Spec.Timeout != nil && b.ko.Spec.Timeout != nil {
		if *a.ko.Spec.Timeout != *b.ko.Spec.Timeout {
			delta.Add("Spec.Timeout", a.ko.Spec.Timeout, b.ko.Spec.Timeout)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.WorkerType, b.ko.Spec.WorkerType) {
		delta.Add("Spec.WorkerType", a.ko.Spec.WorkerType, b.ko.Spec.WorkerType)
	} else if a.ko.Spec.WorkerType != nil && b.ko.Spec.WorkerType != nil {
		if *a.ko.Spec.WorkerType != *b.ko.Spec.WorkerType {
			delta.Add("Spec.WorkerType", a.ko.Spec.WorkerType, b.ko.Spec.WorkerType)
		}
	}

	return delta
}
